[project]
name = "growss"
version = "0.1.0"
description = "GitHub Reusable Workflows for Simulation Systems"
readme = "README.md"
requires-python = ">=3.12.9"
dependencies = [
    "ruff==0.14.4",
    "shellcheck-py==0.11.0.1",
    "yamllint==1.37.1",
]
